export const my_recipe = {
    recipe_1: {
      name: 'Chirashi Don',
      preparation_time: '30 minutes',
      servings: '2',
      ingredients: [
        '1/2 cup rice',
        '1/2 cup water',
        '2 eggs',
        '300g of salmon, tuna and salmon roe',
      ],
      instructions: [
        'Cook rice and water in a rice cooker',
        'Fry eggs in a pan',
        'Serve rice, eggs and fish on a plate',
      ],
      imageName: 'Chirashi',
   
    },
    recipe_2: {
      name: 'Champaran Mutton Curry',
      preparation_time: '35 minutes',
      servings: '4',
      ingredients: [
        '1 Kg mutton',
        '750 gms onion, sliced',
        '2 Garlic cloves (crushed)',
        '6 tbsp ginger-garlic paste',
        '1 tbsp coriander powder',
        '1 tbsp turmeric powder',
        '2 tbsp degi mirch',
        '2 tbsp Kashmiri mirch',
        '2 tbsp lemon juice',
        '150 gms yogurt',
        '1/2 cup mustard oil',
        '1 tsp fennel powder',
        '1 tsp garam masala powder',
        '10 Cloves',
        '8 Black peppercorn',
        '2 inch cinnamon sticks',
        '1 Bay leaf',
        '4 tsp cumin seeds',
        '1 tsp cumin powder, roasted',
        'Wheat dough (atta, to seal the vessel)',
        'to taste salt',
      ],
      instructions: [
        'Marinate the mutton with 3/4th cup of mustard oil and all the remaining ingredients. Keep it aside for 20 minutes.',
        'Take a big earthen pot or a heavy bottom saucepan. Add the remaining oil and the marinated mutton. Put the lid, and seal the edges with dough.',
        'Cook on low heat and then slowly increase the flame to medium and let the mutton cook for 45-50 minutes.',
        'Take out the dough seal after 45 minutes, check if the oil has come up and the mutton is tender and well-cooked.',
        'Garnish with coriander leaves and serve hot.',
      ],
      imageName:"Champaran",
   
    },
  }